# Generated by Django 5.2.1 on 2025-07-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web_demo', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
