# Generated by Django 5.2.1 on 2025-07-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web_demo', '0004_alter_customuser_city_alter_customuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
