# Generated by Django 5.0.6 on 2025-07-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web_demo', '0006_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about',
            field=models.TextField(blank=True, help_text='Additional details about the product.', null=True),
        ),
    ]
