# Generated by Django 5.0.6 on 2025-07-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_web_demo', '0007_product_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
