# Generated by Django 5.0.6 on 2025-07-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web_demo', '0008_auto_20250716_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('women', 'WOMEN'), ('men', 'MEN'), ('boys', 'BOYS'), ('girls', 'GIRLS')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
